name: 💡 Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve Cerulean Reaper? Share it below!

  - type: textarea
    id: idea
    attributes:
      label: Describe the Feature
      description: What do you want to add or improve?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful or necessary?

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Low
        - Medium
        - High
      description: How much value would this add?
